# rebuild system

default: fmt doctor choose

noop:
  @echo ''

choose:
 #@$(gum choose "noop" "system-switch" "home-switch" "flake-update-all" "everything") | xargs just
 @sel=$(gum choose "noop" "system-switch" "home-switch" "flake-update-all" "everything") && [ -n "$sel" ] && just "$sel"

fmt:
  nix fmt

nixos-start-docker-daemon:
  systemctl --user start docker

run *args:
  sudo ./run.sh {{args}}

system-switch: run

home-switch:
  home-manager switch --flake '.#david'

doctor:
  sleipnir-doctor

darwin-switch:
  darwin-rebuild switch --flake '.#fusillade'

everything: update-system update-home system-switch home-switch

##
##

update-system:
  nix flake update nixpkgs

update-home:
  nix flake update nixpkgs-home home-manager neovim-nightly-overlay antigravity-nix

update-all:
  nix flake update

##
##

build:
  just run dry-build --show-trace -v

regenerate-hardware:
   nixos-generate-config --show-hardware-config > hosts/Sleipnir/hardware-configuration.nix
   nix fmt

gc:
  sudo nix-collect-garbage --delete-older-than 14d
  nix-store --gc

melpa-list:
  nix eval --impure --raw --expr 'let f = builtins.getFlake "{{justfile_directory()}}"; pkgs = import f.inputs.nixpkgs { system = builtins.currentSystem; overlays = [ f.inputs.emacs-overlay.overlays.default ]; }; in builtins.concatStringsSep "\n" (builtins.attrNames pkgs.emacsPackages)' > emacs-packages.txt
