run *args:
  sudo ./run.sh {{args}}

darwin-switch:
  darwin-rebuild switch --flake '.#fusillade'

update:
  nix flake update

home-switch:
  home-manager switch --flake './home#david'

home-update:
  nix flake update --flake ./home

build:
  just run dry-build --show-trace -v

regenerate-hardware:
   nixos-generate-config --show-hardware-config > hosts/Sleipnir/hardware-configuration.nix
   nix fmt
