# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "thunderbolt" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/0117327f-b949-42d5-bbd8-d11c590f7ac2";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/C16C-C74C";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  fileSystems."/mnt/500G" = {
    device = "/dev/disk/by-uuid/e31f1ad9-d298-4732-bfab-42c71212d9f7";
    fsType = "ext4";
  };

  fileSystems."/mnt/1TB" = {
    device = "/dev/disk/by-uuid/eddd03f2-61d8-4b5a-98aa-2d06d3211c27";
    fsType = "ext4";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/76b47a65-41c9-424a-a749-deedcdff0e94";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
