# theme = 'monokai_pro_octagon'
theme = 'gruvbox'

[editor.file-picker]
hidden = true # when true, hide .* and gitignored files
follow-symlinks = false 

[editor]
shell = ['zsh', '-c']
scroll-lines = 10
completion-trigger-len = 1
true-color = true
color-modes = true 
idle-timeout = 50
completion-timeout = 50
end-of-line-diagnostics = 'hint'
rulers = [80, 120]
bufferline = 'multiple'
cursorline = true
 # continue-comments = false
undercurl = true
popup-border = "all"
# TODO enable when available
# trim-trailing-whitespace = true
# trim-final-newlines = true
insert-final-newline = true

[editor.cursor-shape]
insert='bar'
select='underline'

[editor.statusline]
left = ['mode', 'spinner', 'file-name', 'read-only-indicator', 'file-modification-indicator']
center = ['version-control','spacer', 'position-percentage', 'file-type', 'file-encoding']
right = ['diagnostics', 'workspace-diagnostics', 'selections','primary-selection-length', 'register', 'position']

[editor.whitespace.render]
space = "none"
newline = "none"
tab = "all"
nbsp = "all"
nnbsp = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.gutters.line-numbers]
min-width = 2

[editor.indent-guides]
render = true 
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"

[editor.lsp]
display-messages = true

[editor.soft-wrap]
enable = true
max-wrap = 30
max-indent-retain = 60

[editor.auto-save]
focus-lost = true

# TODO enable when available - needs newer helix version
# [editor.inline-diagostics]
# cursor-line = 'info'
# other-lines = 'error'

##########################################################
##
## Keybindings 
##
##########################################################
# https://docs.helix-editor.com/keymap.html

##################
### NORMAL #######

[keys.normal]

tab = "move_parent_node_end"
S-tab = "move_parent_node_start"

V = ["goto_first_nonwhitespace", "extend_to_line_end"]
D = ["ensure_selections_forward", "extend_to_line_end"]
H = "goto_first_nonwhitespace"

"+" = "format_selections"
C-t = 'completion'
C-space = "signature_help"

# move line down / up
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

# select & move to next / prev paragraph
"A-j" = ["move_next_word_end", "select_mode", "insert_at_line_start", "move_line_down", "goto_next_paragraph", "normal_mode", "goto_prev_paragraph", "goto_next_paragraph", "trim_selections"]
"A-k" = ["move_next_word_start", "select_mode", "insert_at_line_end", "move_line_up", "goto_prev_paragraph", "normal_mode", "goto_next_paragraph", "goto_prev_paragraph", "trim_selections"]

# move to next / prev paragraph
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"

# Buffers

# great keybinding, but since dumb TTYs see C-[ as Esc we need a failover
"C-[" = ":buffer-previous"
"C-]" = ":buffer-next"

"A-pageup" = ":buffer-previous"
"A-pagedown" = ":buffer-next"

"A-w" = ":buffer-close"

";" = ["collapse_selection", "normal_mode"] # save hitting esc

"!" = ":write"
C-r = [":reload"]

##################
### INSERT #######

[keys.insert]
S-tab = "move_parent_node_start"

A-F = ":format"

################## 
### SELECT #######

[keys.select]
tab = "extend_parent_node_end"
S-tab = "extend_parent_node_start"

V = "extend_to_line_end"
x = "extend_line"

"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"

";" = ["collapse_selection", "normal_mode"] # save hitting esc

##################
### MINOR MODES ##
 
[keys.normal.space]
        
space = "goto_next_buffer"
m = "goto_previous_buffer"

A-F = ":format"
Q = ":quit"
q = ":buffer-close"

[keys.normal.space.l]
a = ":set-option line-number absolute"
r = ":set-option line-number relative"






