# for ZMK
[[language]]
name = "cpp"
file-types = [ "cpp", "h", "keymap", "conf", "dtsi"]

# [[language]]
# name = "text"
# indent = { tab-width = 2, unit = " " }

[language-server.godot]
command = "nc" 
args = [ "127.0.0.1", "6005"]

[[language]]
name = "gdscript"
language-servers = [ "godot" ]

[[language]]
name="rust"
formatter = { command = "rustfmt", args = ["+nightly"]}

# darwin-specific bits here
#
# 
# [language-server.c]
# command = "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang"
# 
# [language-server.omnisharp]
# command = "dotnet"
# args = [ "~/.local/omnisharp/OmniSharp.dll", "--languageserver" ]
# 
# [language-server.c]
# command = "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang"
